services:
  mcp-server:
    build: .
    ports:
      - "${MCP_SERVER_PORT:-8017}:${MCP_SERVER_PORT:-8017}"
    environment:
      - PORTFOLIO_API_URL=${PORTFOLIO_API_URL}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-Hugo Portfolio API Server}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8017}
      - MCP_SERVER_HOST=0.0.0.0
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - ${PORTFOLIO_NETWORK:-betterportfolio_portfolio-dev-network}

networks:
  betterportfolio_portfolio-dev-network:
    external: true
  betterportfolio_portfolio-network:
    external: true
